//! Compatibility dashboard generation.

use std::{
    collections::BTreeMap,
    error::Error,
    path::PathBuf,
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

use cue_rust::{
    Context, DecodeOptions, EncodeOptions, Encoding, LoadConfig, ValidateOptions, decode_bytes,
    encode_value,
};
use serde::Serialize;
use tokio::fs;

static NEXT_FIXTURE_ID: AtomicU64 = AtomicU64::new(0);

#[derive(Debug, Serialize)]
struct CompatibilityReport {
    version: &'static str,
    summary: CompatibilitySummary,
    cases: Vec<CompatibilityCase>,
}

#[derive(Debug, Serialize)]
struct CompatibilitySummary {
    total: usize,
    by_category: BTreeMap<&'static str, usize>,
    by_status: BTreeMap<&'static str, usize>,
}

#[derive(Debug, Serialize)]
struct CompatibilityCase {
    name: &'static str,
    category: &'static str,
    expected: &'static str,
    actual: &'static str,
    status: &'static str,
    reason: Option<&'static str>,
}

#[tokio::test]
#[ignore = "generated by `make compat-report`"]
async fn test_should_generate_compatibility_report() -> Result<(), Box<dyn Error>> {
    let context = Context::new();
    let mut cases = Vec::new();
    push_parser_cases(&context, &mut cases);
    push_semantic_cases(&context, &mut cases)?;
    push_encoding_cases(&context, &mut cases)?;
    push_security_cases(&mut cases);
    push_known_gap_cases(&context, &mut cases).await?;
    assert_supported_cases_pass(&cases)?;

    let report = CompatibilityReport {
        version: cue_rust::VERSION,
        summary: summarize_cases(&cases),
        cases,
    };
    let output = serde_json::to_vec_pretty(&report)?;
    let output_dir = workspace_target_dir().join("compatibility");
    fs::create_dir_all(&output_dir).await?;
    fs::write(output_dir.join("core.json"), output).await?;
    Ok(())
}

fn summarize_cases(cases: &[CompatibilityCase]) -> CompatibilitySummary {
    let mut by_category = BTreeMap::new();
    let mut by_status = BTreeMap::new();
    for case in cases {
        *by_category.entry(case.category).or_insert(0) += 1;
        *by_status.entry(case.status).or_insert(0) += 1;
    }
    CompatibilitySummary {
        total: cases.len(),
        by_category,
        by_status,
    }
}

fn push_parser_cases(context: &Context, cases: &mut Vec<CompatibilityCase>) {
    let parsed = context.parse_source("syntax.cue", "package p\nx: 1\n");
    cases.push(supported_case(
        "syntax/package-field",
        "parser",
        !parsed.diagnostics().has_errors(),
    ));
}

fn push_semantic_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let value = context.compile_source("eval.cue", "x: 1\ny: x\n")?;
    cases.push(supported_case(
        "eval/top-level-reference",
        "semantic",
        value.lookup_path(&["y"])?.kind()? == cue_rust::ValueKind::Number,
    ));

    let nested = context.compile_source("nested.cue", "x: 1\ny: { x: 2, z: x }\n")?;
    cases.push(supported_case(
        "eval/nested-field-reference",
        "semantic",
        nested.lookup_path(&["y", "z"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("2".to_owned()),
    ));

    let let_value = context.compile_source("let.cue", "let x = 1\ny: x\n")?;
    cases.push(supported_case(
        "compile/let-reference",
        "semantic",
        let_value.lookup_path(&["y"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("1".to_owned()),
    ));

    push_alias_cases(context, cases)?;

    let call_value = context.compile_source("call.cue", "x: len([1, 2, 3])\n")?;
    cases.push(supported_case(
        "eval/builtin-len-call",
        "semantic",
        call_value.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("3".to_owned()),
    ));

    push_stdlib_cases(context, cases)?;

    let bytes_value = context.compile_source("bytes.cue", "x: 2 * 'ab'\n")?;
    cases.push(supported_case(
        "eval/bytes-repeat",
        "semantic",
        bytes_value.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Bytes(b"abab".to_vec()),
    ));

    let integer_builtin = context.compile_source("integer.cue", "x: div(-5, 2)\n")?;
    cases.push(supported_case(
        "eval/integer-div-builtin",
        "semantic",
        integer_builtin.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("-3".to_owned()),
    ));

    let disjunction = context.compile_source(
        "disjunction.cue",
        "x: (1 | 2 | 3) & (>=2 & <=2)\ny: *5 | string\nz: or([2, 1, 1, 2]) & 1\n",
    )?;
    cases.push(supported_case(
        "eval/disjunction-bound-intersection",
        "semantic",
        disjunction.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("2".to_owned()),
    ));
    cases.push(supported_case(
        "eval/default-disjunction-selection",
        "semantic",
        disjunction
            .lookup_path(&["y"])?
            .evaluate()?
            .resolve_defaults()
            == cue_rust::EvaluatedValue::Number("5".to_owned()),
    ));
    cases.push(supported_case(
        "eval/builtin-or-call",
        "semantic",
        disjunction.lookup_path(&["z"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("1".to_owned()),
    ));

    let schema = context.compile_source("schema.cue", "name: string\n")?;
    let data = context.compile_source("data.cue", "name: \"cue\"\n")?;
    cases.push(supported_case(
        "vet/string-kind",
        "semantic",
        schema
            .unify(&data)?
            .validate(ValidateOptions::default())
            .is_ok(),
    ));

    let open_list = context.compile_source(
        "open-list.cue",
        "ok: [1, 2, ...>=4 & <=5] & [1, 2, 4, 5]\nbad: [1, 2, ...>=4 & <=5] & [1, 2, 4, 8]\n",
    )?;
    cases.push(supported_case(
        "eval/open-list-ellipsis",
        "semantic",
        open_list.lookup_path(&["ok"])?.evaluate()?
            == cue_rust::EvaluatedValue::List(vec![
                cue_rust::EvaluatedValue::Number("1".to_owned()),
                cue_rust::EvaluatedValue::Number("2".to_owned()),
                cue_rust::EvaluatedValue::Number("4".to_owned()),
                cue_rust::EvaluatedValue::Number("5".to_owned()),
            ])
            && open_list
                .lookup_path(&["bad"])?
                .validate(ValidateOptions::default())
                .is_err(),
    ));
    Ok(())
}

fn push_alias_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let alias_value =
        context.compile_source("alias.cue", "t: {\n  _a: b\n  let b = c\n  c=d: 3\n}\n")?;
    cases.push(supported_case(
        "compile/aliases",
        "semantic",
        alias_value.lookup_path(&["t", "_a"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("3".to_owned())
            && alias_value.lookup_path(&["t", "d"])?.evaluate()?
                == cue_rust::EvaluatedValue::Number("3".to_owned())
            && alias_value.lookup_path(&["t", "c"]).is_err(),
    ));
    Ok(())
}

fn push_stdlib_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let standard_imports = context.compile_source(
        "stdlib.cue",
        "import \"strings\"\nimport \"list\"\ntext: strings.ToUpper(strings.TrimSpace(\" cue \
         \"))\njoined: strings.Join([\"cue\", \"rust\"], \"-\")\nhas: list.Contains([\"cue\", \
         \"rust\"], \"rust\")\nrepeated: list.Repeat([1], 3)\nconcatenated: list.Concat([[1], [2, \
         3]])\n",
    )?;
    cases.push(supported_case(
        "eval/stdlib-strings-import",
        "semantic",
        standard_imports.lookup_path(&["text"])?.evaluate()?
            == cue_rust::EvaluatedValue::String("CUE".to_owned())
            && standard_imports.lookup_path(&["joined"])?.evaluate()?
                == cue_rust::EvaluatedValue::String("cue-rust".to_owned()),
    ));
    cases.push(supported_case(
        "eval/stdlib-list-import",
        "semantic",
        standard_imports.lookup_path(&["has"])?.evaluate()? == cue_rust::EvaluatedValue::Bool(true)
            && standard_imports.lookup_path(&["repeated"])?.evaluate()?
                == cue_rust::EvaluatedValue::List(vec![
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                ])
            && standard_imports
                .lookup_path(&["concatenated"])?
                .evaluate()?
                == cue_rust::EvaluatedValue::List(vec![
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                    cue_rust::EvaluatedValue::Number("2".to_owned()),
                    cue_rust::EvaluatedValue::Number("3".to_owned()),
                ]),
    ));

    let broad_strings = context.compile_source(
        "stdlib-strings.cue",
        "import \"strings\"\ncompare: strings.Compare(\"a\", \"b\")\ncontainsAny: \
         strings.ContainsAny(\"cue\", \"xzue\")\nlastIndex: strings.LastIndex(\"banana\", \
         \"na\")\nsplitAfterN: strings.SplitAfterN(\"a,b,c\", \",\", 2)\nfields: \
         strings.Fields(\"  a b \")\ntrim: strings.Trim(\"abba\", \"a\")\nreplace: \
         strings.Replace(\"banana\", \"na\", \"NA\", 1)\nrunes: strings.Runes(\"Café\")\n",
    )?;
    cases.push(supported_case(
        "eval/stdlib-strings-full-surface",
        "semantic",
        broad_strings.lookup_path(&["compare"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("-1".to_owned())
            && broad_strings.lookup_path(&["containsAny"])?.evaluate()?
                == cue_rust::EvaluatedValue::Bool(true)
            && broad_strings.lookup_path(&["lastIndex"])?.evaluate()?
                == cue_rust::EvaluatedValue::Number("4".to_owned())
            && broad_strings.lookup_path(&["splitAfterN"])?.kind()? == cue_rust::ValueKind::List
            && broad_strings.lookup_path(&["fields"])?.kind()? == cue_rust::ValueKind::List
            && broad_strings.lookup_path(&["trim"])?.evaluate()?
                == cue_rust::EvaluatedValue::String("bb".to_owned())
            && broad_strings.lookup_path(&["replace"])?.evaluate()?
                == cue_rust::EvaluatedValue::String("baNAna".to_owned())
            && broad_strings.lookup_path(&["runes"])?.kind()? == cue_rust::ValueKind::List,
    ));

    let broad_list = context.compile_source(
        "stdlib-list.cue",
        "import \"list\"\nflatten: list.FlattenN([1, [[2, 3], []], [4]], 2)\nrange: list.Range(0, \
         5, 2)\nsorted: list.SortStrings([\"b\", \"a\"])\nsum: list.Sum([1, 2, 3])\nunique: \
         list.UniqueItems([1, 2, 1])\n",
    )?;
    cases.push(supported_case(
        "eval/stdlib-list-broad-surface",
        "semantic",
        broad_list.lookup_path(&["flatten"])?.kind()? == cue_rust::ValueKind::List
            && broad_list.lookup_path(&["range"])?.kind()? == cue_rust::ValueKind::List
            && broad_list.lookup_path(&["sorted"])?.kind()? == cue_rust::ValueKind::List
            && broad_list.lookup_path(&["sum"])?.evaluate()?
                == cue_rust::EvaluatedValue::Number("6".to_owned())
            && broad_list.lookup_path(&["unique"])?.evaluate()?
                == cue_rust::EvaluatedValue::Bool(false),
    ));
    Ok(())
}

fn push_encoding_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let export_value = context.compile_source("export.cue", "x: 1\n")?;
    let mut options = EncodeOptions::default();
    options.encoding = Encoding::Json;
    cases.push(supported_case(
        "export/json-object",
        "encoding",
        encode_value(&export_value, options)?.contains("\"x\": 1"),
    ));
    Ok(())
}

fn push_security_cases(cases: &mut Vec<CompatibilityCase>) {
    let mut limited_decode = DecodeOptions::default();
    limited_decode.max_depth = 0;
    cases.push(supported_case(
        "decode/depth-limit",
        "security",
        decode_bytes(Encoding::Json, br#"{"x":1}"#, limited_decode).is_err(),
    ));
}

async fn push_known_gap_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    cases.push(supported_case(
        "compile/unsupported-import-diagnostic",
        "loader-gap",
        context
            .compile_source("import.cue", "import \"example.com/remote/pkg\"\nx: 1\n")
            .is_err(),
    ));

    let loader_passed = local_import_registry_case(context)
        .await
        .is_ok_and(|passed| passed);
    cases.push(supported_case(
        "loader/import-registry",
        "loader-gap",
        loader_passed,
    ));
    push_phase9_parity_cases(context, cases);
    cases.push(expected_gap_case(
        "eval/cycle-scheduler",
        "semantic-gap",
        "inline and top-level structural/list cycles now resolve for the currently covered vendor \
         cases, but full upstream cycle scheduling still needs public structural-cycle \
         diagnostics, broader structural-cycle coverage, and lazy disjunction/default fixpoint \
         support",
    ));
    Ok(())
}

async fn local_import_registry_case(context: &Context) -> Result<bool, Box<dyn Error>> {
    let root = fixture_dir().await?;
    let import_dir = root.join("cue.mod/pkg/example.com/lib");
    let dep_dir = root.join("cue.mod/pkg/example.com/dep");
    fs::create_dir_all(&import_dir).await?;
    fs::create_dir_all(&dep_dir).await?;
    fs::write(
        root.join("main.cue"),
        "package p\nimport \"example.com/lib\"\nout: lib.value\n",
    )
    .await?;
    fs::write(
        import_dir.join("lib.cue"),
        "package lib\nimport \"example.com/dep\"\nvalue: dep.value + 1\n",
    )
    .await?;
    fs::write(dep_dir.join("dep.cue"), "package dep\nvalue: 2\n").await?;
    let instances = context
        .load(
            LoadConfig::builder()
                .current_dir(Some(root.clone()))
                .module_root(Some(root))
                .build(),
            &[PathBuf::from(".").try_into()?],
        )
        .await?;
    let Some(instance) = instances.first() else {
        return Ok(false);
    };
    let value = context.build_instance(instance)?;
    Ok(
        value.lookup_path(&["out"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("3".to_owned()),
    )
}

fn push_phase9_parity_cases(context: &Context, cases: &mut Vec<CompatibilityCase>) {
    let Ok(value) = context.compile_source(
        "phase9-parity.cue",
        "import \"list\"\nkey: \"name\"\ninterpolated: \"v=\\(1+1)\"\ndynamic: {(key): \
         \"cue\"}\nsource: {b: 1, c: 2}\nfields: {for k, v in source {\"\\(k)\": v + 1}}\nitems: \
         [for x in [1, 2, 3] if x > 1 {x}]\nsorted: list.Sort([2, 1], list.Ascending)\ndir: \
         list.Ascending\nsortedAlias: list.Sort([2, 1], dir)\ncmp: {x: _, y: _, less: x.a < \
         y.a}\ncustom: list.Sort([{a: 2}, {a: 1}], {x: _, y: _, less: x.a < y.a})\ncustomNamed: \
         list.Sort([{a: 2}, {a: 1}], cmp)\nbadComparatorSchema: list.Sort([\"b\", \"a\"], {x: \
         int, y: int, less: false})\npattern: {[string]: int, a: 1}\npatternBad: {[string]: int} \
         & {a: \"bad\"}\n#ClosedDef: {env: a: \"A\", env: b: \"B\"}\nclosedDefinitionBad: \
         #ClosedDef & {env: c: \"C\"}\nclosedPatternOk: close({[=~\"^a\"]: string}) & {apple: \
         \"ok\"}\nclosedPatternBad: close({[=~\"^a\"]: string}) & {banana: \
         \"bad\"}\ncloseShallow: close({a: b: int}) & {a: c: int}\ntautologicalList: {t0: c: \
         [c[0]], pair: c: [c[1], c[0]]}\ngroundedList: {a: 100, p1: c: [c[1], a], p2: c: [a, \
         c[0]]}\nrootListValue: 100\nrootListT0: [rootListT0[0]]\nrootListPair: [rootListPair[1], \
         rootListPair[0]]\nrootListGrounded: [rootListGrounded[1], rootListValue]\nstructCycle: \
         {self: s1: s1 & {a: 1}, two: {s1: s2 & {a: 1}, s2: s1 & {b: 2}}, three: {s1: s2 & {a: \
         1}, s2: s3 & {b: 2}, s3: s1 & {c: 3}}}\nstructuralBad: {a: c: a}\ninvalidDynamic: {(1): \
         1}\ncycle: cycle\n",
    ) else {
        cases.push(supported_case("phase9/parity-tranche", "semantic", false));
        return;
    };

    push_phase9_parser_cases(&value, cases);
    push_phase9_list_cases(&value, cases);
    push_phase9_semantic_cases(&value, cases);
}

fn push_phase9_parser_cases(value: &cue_rust::Value, cases: &mut Vec<CompatibilityCase>) {
    let interpolation_passed = value
        .lookup_path(&["interpolated"])
        .and_then(|value| value.evaluate())
        .is_ok_and(|value| value == cue_rust::EvaluatedValue::String("v=2".to_owned()));
    cases.push(supported_case(
        "syntax/string-interpolation",
        "parser-gap",
        interpolation_passed,
    ));

    let dynamic_passed = value
        .lookup_path(&["dynamic", "name"])
        .and_then(|value| value.evaluate())
        .is_ok_and(|value| value == cue_rust::EvaluatedValue::String("cue".to_owned()));
    cases.push(supported_case(
        "syntax/dynamic-labels",
        "parser-gap",
        dynamic_passed,
    ));

    let comprehension_passed = value
        .lookup_path(&["fields", "b"])
        .and_then(|value| value.evaluate())
        .is_ok_and(|value| value == cue_rust::EvaluatedValue::Number("2".to_owned()))
        && value
            .lookup_path(&["items"])
            .and_then(|value| value.evaluate())
            .is_ok_and(|value| {
                value
                    == cue_rust::EvaluatedValue::List(vec![
                        cue_rust::EvaluatedValue::Number("2".to_owned()),
                        cue_rust::EvaluatedValue::Number("3".to_owned()),
                    ])
            });
    cases.push(supported_case(
        "syntax/comprehensions",
        "parser-gap",
        comprehension_passed,
    ));
}

fn push_phase9_list_cases(value: &cue_rust::Value, cases: &mut Vec<CompatibilityCase>) {
    let sort_passed = sorted_number_list_matches(value, "sorted", &["1", "2"]);
    cases.push(supported_case(
        "stdlib/list-sort-constants",
        "stdlib-gap",
        sort_passed,
    ));

    let sort_alias_passed = sorted_number_list_matches(value, "sortedAlias", &["1", "2"]);
    cases.push(supported_case(
        "stdlib/list-sort-constant-alias",
        "stdlib-gap",
        sort_alias_passed,
    ));

    let comparator_passed = custom_sort_field_order(value, "custom")
        .is_ok_and(|actual| actual == vec!["1".to_owned(), "2".to_owned()])
        && custom_sort_field_order(value, "customNamed")
            .is_ok_and(|actual| actual == vec!["1".to_owned(), "2".to_owned()])
        && value
            .lookup_path(&["badComparatorSchema"])
            .and_then(|value| value.validate(ValidateOptions::default()))
            .is_err();
    cases.push(supported_case(
        "stdlib/list-comparator-schema-surface",
        "stdlib-gap",
        comparator_passed,
    ));
}

fn push_phase9_semantic_cases(value: &cue_rust::Value, cases: &mut Vec<CompatibilityCase>) {
    let pattern_passed = value
        .lookup_path(&["pattern", "a"])
        .and_then(|value| value.evaluate())
        .is_ok_and(|value| value == cue_rust::EvaluatedValue::Number("1".to_owned()))
        && value
            .lookup_path(&["patternBad"])
            .and_then(|value| value.validate(ValidateOptions::default()))
            .is_err();
    cases.push(supported_case(
        "eval/pattern-label-constraints",
        "semantic-gap",
        pattern_passed,
    ));

    let closedness_passed = value
        .lookup_path(&["closedDefinitionBad"])
        .and_then(|value| value.validate(ValidateOptions::default()))
        .is_err()
        && value
            .lookup_path(&["closedPatternOk", "apple"])
            .and_then(|value| value.evaluate())
            .is_ok_and(|value| value == cue_rust::EvaluatedValue::String("ok".to_owned()))
        && value
            .lookup_path(&["closedPatternBad"])
            .and_then(|value| value.validate(ValidateOptions::default()))
            .is_err()
        && value.lookup_path(&["closeShallow"]).is_ok_and(|value| {
            value
                .lookup_path(&["a", "c"])
                .and_then(|value| value.evaluate())
                .is_ok_and(|value| value.kind() == cue_rust::ValueKind::Int)
        });
    cases.push(supported_case(
        "eval/closedness-patterns",
        "semantic-gap",
        closedness_passed,
    ));

    let invalid_dynamic_passed = value
        .lookup_path(&["invalidDynamic"])
        .and_then(|value| value.validate(ValidateOptions::default()))
        .is_err();
    cases.push(supported_case(
        "eval/dynamic-label-type-check",
        "semantic-gap",
        invalid_dynamic_passed,
    ));

    let cycle_passed = value
        .lookup_path(&["cycle"])
        .and_then(|value| value.validate(ValidateOptions::default()))
        .is_err();
    cases.push(supported_case(
        "eval/cycle-safe-cache",
        "semantic-gap",
        cycle_passed,
    ));
    push_phase9_cycle_cases(value, cases);
}

fn push_phase9_cycle_cases(value: &cue_rust::Value, cases: &mut Vec<CompatibilityCase>) {
    cases.push(supported_case(
        "eval/tautological-list-cycle",
        "semantic-gap",
        tautological_list_cycles_pass(value),
    ));

    cases.push(supported_case(
        "eval/grounded-list-cycle",
        "semantic-gap",
        grounded_list_cycles_pass(value),
    ));

    cases.push(supported_case(
        "eval/top-level-list-cycle",
        "semantic-gap",
        top_level_list_cycles_pass(value),
    ));

    cases.push(supported_case(
        "eval/structural-cycle-fixpoint",
        "semantic-gap",
        structural_cycle_fixpoints_pass(value),
    ));

    cases.push(supported_case(
        "eval/structural-cycle-bottom",
        "semantic-gap",
        structural_cycle_bottom_passes(value),
    ));
}

fn tautological_list_cycles_pass(value: &cue_rust::Value) -> bool {
    evaluated_path_eq(
        value,
        &["tautologicalList", "t0", "c"],
        &cue_rust::EvaluatedValue::List(vec![cue_rust::EvaluatedValue::Top]),
    ) && evaluated_path_eq(value, &["tautologicalList", "pair", "c"], &top_pair_value())
}

fn grounded_list_cycles_pass(value: &cue_rust::Value) -> bool {
    evaluated_path_eq(value, &["groundedList", "p1", "c"], &hundred_pair_value())
        && evaluated_path_eq(value, &["groundedList", "p2", "c"], &hundred_pair_value())
}

fn top_level_list_cycles_pass(value: &cue_rust::Value) -> bool {
    evaluated_path_eq(
        value,
        &["rootListT0"],
        &cue_rust::EvaluatedValue::List(vec![cue_rust::EvaluatedValue::Top]),
    ) && evaluated_path_eq(value, &["rootListPair"], &top_pair_value())
        && evaluated_path_eq(value, &["rootListGrounded"], &hundred_pair_value())
}

fn structural_cycle_fixpoints_pass(value: &cue_rust::Value) -> bool {
    evaluated_path_number(value, &["structCycle", "self", "s1", "a"], "1")
        && evaluated_path_number(value, &["structCycle", "two", "s1", "b"], "2")
        && evaluated_path_number(value, &["structCycle", "two", "s2", "a"], "1")
        && evaluated_path_number(value, &["structCycle", "three", "s1", "c"], "3")
        && evaluated_path_number(value, &["structCycle", "three", "s2", "a"], "1")
        && evaluated_path_number(value, &["structCycle", "three", "s3", "b"], "2")
}

fn structural_cycle_bottom_passes(value: &cue_rust::Value) -> bool {
    value
        .lookup_path(&["structuralBad", "a", "c"])
        .and_then(|value| value.evaluate())
        .is_ok_and(|value| {
            matches!(
                value,
                cue_rust::EvaluatedValue::Bottom(bottom)
                    if bottom.code == "cue.eval.structural_cycle"
            )
        })
}

fn evaluated_path_number(value: &cue_rust::Value, path: &[&str], expected: &str) -> bool {
    evaluated_path_eq(
        value,
        path,
        &cue_rust::EvaluatedValue::Number(expected.to_owned()),
    )
}

fn evaluated_path_eq(
    value: &cue_rust::Value,
    path: &[&str],
    expected: &cue_rust::EvaluatedValue,
) -> bool {
    value
        .lookup_path(path)
        .and_then(|value| value.evaluate())
        .is_ok_and(|value| value == *expected)
}

fn top_pair_value() -> cue_rust::EvaluatedValue {
    cue_rust::EvaluatedValue::List(vec![
        cue_rust::EvaluatedValue::Top,
        cue_rust::EvaluatedValue::Top,
    ])
}

fn hundred_pair_value() -> cue_rust::EvaluatedValue {
    cue_rust::EvaluatedValue::List(vec![
        cue_rust::EvaluatedValue::Number("100".to_owned()),
        cue_rust::EvaluatedValue::Number("100".to_owned()),
    ])
}

fn sorted_number_list_matches(value: &cue_rust::Value, field: &str, expected: &[&str]) -> bool {
    let expected = cue_rust::EvaluatedValue::List(
        expected
            .iter()
            .map(|value| cue_rust::EvaluatedValue::Number((*value).to_owned()))
            .collect(),
    );
    value
        .lookup_path(&[field])
        .and_then(|value| value.evaluate())
        .is_ok_and(|value| value == expected)
}

fn custom_sort_field_order(
    value: &cue_rust::Value,
    field: &str,
) -> Result<Vec<String>, Box<dyn Error>> {
    let cue_rust::EvaluatedValue::List(items) = value.lookup_path(&[field])?.evaluate()? else {
        return Err(format!("{field}: expected list").into());
    };
    items
        .into_iter()
        .map(|item| {
            let cue_rust::EvaluatedValue::Struct(fields) = item else {
                return Err(format!("{field}: expected struct item").into());
            };
            let Some(cue_rust::EvaluatedValue::Number(value)) = fields.get("a") else {
                return Err(format!("{field}: missing numeric field a").into());
            };
            Ok(value.clone())
        })
        .collect()
}

fn supported_case(name: &'static str, category: &'static str, passed: bool) -> CompatibilityCase {
    CompatibilityCase {
        name,
        category,
        expected: "pass",
        actual: actual_status(passed),
        status: if passed { "pass" } else { "regression" },
        reason: None,
    }
}

fn expected_gap_case(
    name: &'static str,
    category: &'static str,
    reason: &'static str,
) -> CompatibilityCase {
    CompatibilityCase {
        name,
        category,
        expected: "expected-fail",
        actual: "fail",
        status: "expected-fail",
        reason: Some(reason),
    }
}

fn actual_status(passed: bool) -> &'static str {
    if passed { "pass" } else { "fail" }
}

async fn fixture_dir() -> Result<camino::Utf8PathBuf, Box<dyn Error>> {
    let nanos = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos();
    let suffix = NEXT_FIXTURE_ID.fetch_add(1, Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!("cue-rust-compat-{nanos}-{suffix}"));
    fs::create_dir_all(&path).await?;
    camino::Utf8PathBuf::from_path_buf(path)
        .map_err(|path| format!("non-UTF-8 path: {}", path.display()).into())
}

fn assert_supported_cases_pass(cases: &[CompatibilityCase]) -> Result<(), Box<dyn Error>> {
    let regressions = cases
        .iter()
        .filter(|case| case.expected == "pass" && case.actual != "pass")
        .map(|case| case.name)
        .collect::<Vec<_>>();
    if regressions.is_empty() {
        return Ok(());
    }
    Err(format!("supported compatibility cases regressed: {regressions:?}").into())
}

fn workspace_target_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("target")
}
