//! Compatibility dashboard generation.

use std::{error::Error, path::PathBuf};

use cue_rust::{
    Context, DecodeOptions, EncodeOptions, Encoding, ValidateOptions, decode_bytes, encode_value,
};
use serde::Serialize;
use tokio::fs;

#[derive(Debug, Serialize)]
struct CompatibilityReport {
    version: &'static str,
    cases: Vec<CompatibilityCase>,
}

#[derive(Debug, Serialize)]
struct CompatibilityCase {
    name: &'static str,
    category: &'static str,
    status: &'static str,
}

#[tokio::test]
#[ignore = "generated by `make compat-report`"]
async fn test_should_generate_compatibility_report() -> Result<(), Box<dyn Error>> {
    let context = Context::new();
    let mut cases = Vec::new();

    let parsed = context.parse_source("syntax.cue", "package p\nx: 1\n");
    cases.push(case(
        "syntax/package-field",
        "parser",
        pass_status(!parsed.diagnostics().has_errors()),
    ));

    let value = context.compile_source("eval.cue", "x: 1\ny: x\n")?;
    cases.push(case(
        "eval/top-level-reference",
        "semantic",
        pass_status(value.lookup_path(&["y"])?.kind()? == cue_rust::ValueKind::Number),
    ));

    let nested = context.compile_source("nested.cue", "x: 1\ny: { x: 2, z: x }\n")?;
    cases.push(case(
        "eval/nested-field-reference",
        "semantic",
        pass_status(
            nested.lookup_path(&["y", "z"])?.evaluate()?
                == cue_rust::EvaluatedValue::Number("2".to_owned()),
        ),
    ));

    let let_value = context.compile_source("let.cue", "let x = 1\ny: x\n")?;
    cases.push(case(
        "compile/let-reference",
        "semantic",
        pass_status(
            let_value.lookup_path(&["y"])?.evaluate()?
                == cue_rust::EvaluatedValue::Number("1".to_owned()),
        ),
    ));

    let call_value = context.compile_source("call.cue", "x: len([1, 2, 3])\n")?;
    cases.push(case(
        "eval/builtin-len-call",
        "semantic",
        pass_status(
            call_value.lookup_path(&["x"])?.evaluate()?
                == cue_rust::EvaluatedValue::Number("3".to_owned()),
        ),
    ));

    let schema = context.compile_source("schema.cue", "name: string\n")?;
    let data = context.compile_source("data.cue", "name: \"cue\"\n")?;
    cases.push(case(
        "vet/string-kind",
        "semantic",
        pass_status(
            schema
                .unify(&data)?
                .validate(ValidateOptions::default())
                .is_ok(),
        ),
    ));

    let export_value = context.compile_source("export.cue", "x: 1\n")?;
    let mut options = EncodeOptions::default();
    options.encoding = Encoding::Json;
    cases.push(case(
        "export/json-object",
        "encoding",
        pass_status(encode_value(&export_value, options)?.contains("\"x\": 1")),
    ));

    let mut limited_decode = DecodeOptions::default();
    limited_decode.max_depth = 0;
    cases.push(case(
        "decode/depth-limit",
        "security",
        pass_status(decode_bytes(Encoding::Json, br#"{"x":1}"#, limited_decode).is_err()),
    ));

    cases.push(case(
        "compile/import-diagnostic",
        "loader-gap",
        pass_status(
            context
                .compile_source("import.cue", "import \"strings\"\nx: 1\n")
                .is_err(),
        ),
    ));

    cases.push(case(
        "loader/import-registry",
        "loader-gap",
        "expected-fail",
    ));

    let report = CompatibilityReport {
        version: cue_rust::VERSION,
        cases,
    };
    let output = serde_json::to_vec_pretty(&report)?;
    let output_dir = workspace_target_dir().join("compatibility");
    fs::create_dir_all(&output_dir).await?;
    fs::write(output_dir.join("core.json"), output).await?;
    Ok(())
}

fn case(name: &'static str, category: &'static str, status: &'static str) -> CompatibilityCase {
    CompatibilityCase {
        name,
        category,
        status,
    }
}

fn pass_status(passed: bool) -> &'static str {
    if passed { "pass" } else { "expected-fail" }
}

fn workspace_target_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("target")
}
