//! Compatibility dashboard generation.

use std::{collections::BTreeMap, error::Error, path::PathBuf};

use cue_rust::{
    Context, DecodeOptions, EncodeOptions, Encoding, ValidateOptions, decode_bytes, encode_value,
};
use serde::Serialize;
use tokio::fs;

#[derive(Debug, Serialize)]
struct CompatibilityReport {
    version: &'static str,
    summary: CompatibilitySummary,
    cases: Vec<CompatibilityCase>,
}

#[derive(Debug, Serialize)]
struct CompatibilitySummary {
    total: usize,
    by_category: BTreeMap<&'static str, usize>,
    by_status: BTreeMap<&'static str, usize>,
}

#[derive(Debug, Serialize)]
struct CompatibilityCase {
    name: &'static str,
    category: &'static str,
    expected: &'static str,
    actual: &'static str,
    status: &'static str,
    reason: Option<&'static str>,
}

#[tokio::test]
#[ignore = "generated by `make compat-report`"]
async fn test_should_generate_compatibility_report() -> Result<(), Box<dyn Error>> {
    let context = Context::new();
    let mut cases = Vec::new();
    push_parser_cases(&context, &mut cases);
    push_semantic_cases(&context, &mut cases)?;
    push_encoding_cases(&context, &mut cases)?;
    push_security_cases(&mut cases);
    push_known_gap_cases(&context, &mut cases);
    assert_supported_cases_pass(&cases)?;

    let report = CompatibilityReport {
        version: cue_rust::VERSION,
        summary: summarize_cases(&cases),
        cases,
    };
    let output = serde_json::to_vec_pretty(&report)?;
    let output_dir = workspace_target_dir().join("compatibility");
    fs::create_dir_all(&output_dir).await?;
    fs::write(output_dir.join("core.json"), output).await?;
    Ok(())
}

fn summarize_cases(cases: &[CompatibilityCase]) -> CompatibilitySummary {
    let mut by_category = BTreeMap::new();
    let mut by_status = BTreeMap::new();
    for case in cases {
        *by_category.entry(case.category).or_insert(0) += 1;
        *by_status.entry(case.status).or_insert(0) += 1;
    }
    CompatibilitySummary {
        total: cases.len(),
        by_category,
        by_status,
    }
}

fn push_parser_cases(context: &Context, cases: &mut Vec<CompatibilityCase>) {
    let parsed = context.parse_source("syntax.cue", "package p\nx: 1\n");
    cases.push(supported_case(
        "syntax/package-field",
        "parser",
        !parsed.diagnostics().has_errors(),
    ));
}

fn push_semantic_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let value = context.compile_source("eval.cue", "x: 1\ny: x\n")?;
    cases.push(supported_case(
        "eval/top-level-reference",
        "semantic",
        value.lookup_path(&["y"])?.kind()? == cue_rust::ValueKind::Number,
    ));

    let nested = context.compile_source("nested.cue", "x: 1\ny: { x: 2, z: x }\n")?;
    cases.push(supported_case(
        "eval/nested-field-reference",
        "semantic",
        nested.lookup_path(&["y", "z"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("2".to_owned()),
    ));

    let let_value = context.compile_source("let.cue", "let x = 1\ny: x\n")?;
    cases.push(supported_case(
        "compile/let-reference",
        "semantic",
        let_value.lookup_path(&["y"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("1".to_owned()),
    ));

    push_alias_cases(context, cases)?;

    let call_value = context.compile_source("call.cue", "x: len([1, 2, 3])\n")?;
    cases.push(supported_case(
        "eval/builtin-len-call",
        "semantic",
        call_value.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("3".to_owned()),
    ));

    push_stdlib_cases(context, cases)?;

    let bytes_value = context.compile_source("bytes.cue", "x: 2 * 'ab'\n")?;
    cases.push(supported_case(
        "eval/bytes-repeat",
        "semantic",
        bytes_value.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Bytes(b"abab".to_vec()),
    ));

    let integer_builtin = context.compile_source("integer.cue", "x: div(-5, 2)\n")?;
    cases.push(supported_case(
        "eval/integer-div-builtin",
        "semantic",
        integer_builtin.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("-3".to_owned()),
    ));

    let disjunction = context.compile_source(
        "disjunction.cue",
        "x: (1 | 2 | 3) & (>=2 & <=2)\ny: *5 | string\nz: or([2, 1, 1, 2]) & 1\n",
    )?;
    cases.push(supported_case(
        "eval/disjunction-bound-intersection",
        "semantic",
        disjunction.lookup_path(&["x"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("2".to_owned()),
    ));
    cases.push(supported_case(
        "eval/default-disjunction-selection",
        "semantic",
        disjunction
            .lookup_path(&["y"])?
            .evaluate()?
            .resolve_defaults()
            == cue_rust::EvaluatedValue::Number("5".to_owned()),
    ));
    cases.push(supported_case(
        "eval/builtin-or-call",
        "semantic",
        disjunction.lookup_path(&["z"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("1".to_owned()),
    ));

    let schema = context.compile_source("schema.cue", "name: string\n")?;
    let data = context.compile_source("data.cue", "name: \"cue\"\n")?;
    cases.push(supported_case(
        "vet/string-kind",
        "semantic",
        schema
            .unify(&data)?
            .validate(ValidateOptions::default())
            .is_ok(),
    ));

    let open_list = context.compile_source(
        "open-list.cue",
        "ok: [1, 2, ...>=4 & <=5] & [1, 2, 4, 5]\nbad: [1, 2, ...>=4 & <=5] & [1, 2, 4, 8]\n",
    )?;
    cases.push(supported_case(
        "eval/open-list-ellipsis",
        "semantic",
        open_list.lookup_path(&["ok"])?.evaluate()?
            == cue_rust::EvaluatedValue::List(vec![
                cue_rust::EvaluatedValue::Number("1".to_owned()),
                cue_rust::EvaluatedValue::Number("2".to_owned()),
                cue_rust::EvaluatedValue::Number("4".to_owned()),
                cue_rust::EvaluatedValue::Number("5".to_owned()),
            ])
            && open_list
                .lookup_path(&["bad"])?
                .validate(ValidateOptions::default())
                .is_err(),
    ));
    Ok(())
}

fn push_alias_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let alias_value =
        context.compile_source("alias.cue", "t: {\n  _a: b\n  let b = c\n  c=d: 3\n}\n")?;
    cases.push(supported_case(
        "compile/aliases",
        "semantic",
        alias_value.lookup_path(&["t", "_a"])?.evaluate()?
            == cue_rust::EvaluatedValue::Number("3".to_owned())
            && alias_value.lookup_path(&["t", "d"])?.evaluate()?
                == cue_rust::EvaluatedValue::Number("3".to_owned())
            && alias_value.lookup_path(&["t", "c"]).is_err(),
    ));
    Ok(())
}

fn push_stdlib_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let standard_imports = context.compile_source(
        "stdlib.cue",
        "import \"strings\"\nimport \"list\"\ntext: strings.ToUpper(strings.TrimSpace(\" cue \
         \"))\njoined: strings.Join([\"cue\", \"rust\"], \"-\")\nhas: list.Contains([\"cue\", \
         \"rust\"], \"rust\")\nrepeated: list.Repeat([1], 3)\nconcatenated: list.Concat([[1], [2, \
         3]])\n",
    )?;
    cases.push(supported_case(
        "eval/stdlib-strings-import",
        "semantic",
        standard_imports.lookup_path(&["text"])?.evaluate()?
            == cue_rust::EvaluatedValue::String("CUE".to_owned())
            && standard_imports.lookup_path(&["joined"])?.evaluate()?
                == cue_rust::EvaluatedValue::String("cue-rust".to_owned()),
    ));
    cases.push(supported_case(
        "eval/stdlib-list-import",
        "semantic",
        standard_imports.lookup_path(&["has"])?.evaluate()? == cue_rust::EvaluatedValue::Bool(true)
            && standard_imports.lookup_path(&["repeated"])?.evaluate()?
                == cue_rust::EvaluatedValue::List(vec![
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                ])
            && standard_imports
                .lookup_path(&["concatenated"])?
                .evaluate()?
                == cue_rust::EvaluatedValue::List(vec![
                    cue_rust::EvaluatedValue::Number("1".to_owned()),
                    cue_rust::EvaluatedValue::Number("2".to_owned()),
                    cue_rust::EvaluatedValue::Number("3".to_owned()),
                ]),
    ));
    Ok(())
}

fn push_encoding_cases(
    context: &Context,
    cases: &mut Vec<CompatibilityCase>,
) -> Result<(), Box<dyn Error>> {
    let export_value = context.compile_source("export.cue", "x: 1\n")?;
    let mut options = EncodeOptions::default();
    options.encoding = Encoding::Json;
    cases.push(supported_case(
        "export/json-object",
        "encoding",
        encode_value(&export_value, options)?.contains("\"x\": 1"),
    ));
    Ok(())
}

fn push_security_cases(cases: &mut Vec<CompatibilityCase>) {
    let mut limited_decode = DecodeOptions::default();
    limited_decode.max_depth = 0;
    cases.push(supported_case(
        "decode/depth-limit",
        "security",
        decode_bytes(Encoding::Json, br#"{"x":1}"#, limited_decode).is_err(),
    ));
}

fn push_known_gap_cases(context: &Context, cases: &mut Vec<CompatibilityCase>) {
    cases.push(supported_case(
        "compile/unsupported-import-diagnostic",
        "loader-gap",
        context
            .compile_source("import.cue", "import \"example.com/remote/pkg\"\nx: 1\n")
            .is_err(),
    ));

    cases.push(expected_gap_case(
        "loader/import-registry",
        "loader-gap",
        "registry imports are outside the Phase 9 local-loader compatibility subset",
    ));
    cases.push(expected_gap_case(
        "stdlib/strings-full-surface",
        "stdlib-gap",
        "only high-frequency strings functions are implemented; remaining upstream strings \
         builtins are tracked separately",
    ));
    cases.push(expected_gap_case(
        "stdlib/list-full-surface",
        "stdlib-gap",
        "only high-frequency list functions are implemented; validators, sorting, and aggregate \
         list builtins remain gaps",
    ));
    cases.push(expected_gap_case(
        "syntax/string-interpolation",
        "parser-gap",
        "scanner currently tokenizes strings as literals and does not split interpolation segments",
    ));
    cases.push(expected_gap_case(
        "syntax/comprehensions",
        "parser-gap",
        "for/if comprehensions require dedicated AST and ADT forms before evaluation",
    ));
    cases.push(expected_gap_case(
        "syntax/dynamic-labels",
        "parser-gap",
        "dynamic and pattern labels are not yet represented as first-class labels",
    ));
    cases.push(expected_gap_case(
        "eval/cycle-scheduler",
        "semantic-gap",
        "structural cycle detection still relies on depth limits instead of upstream-style \
         scheduling",
    ));
    cases.push(expected_gap_case(
        "eval/closedness-patterns",
        "semantic-gap",
        "closedness is limited to close() and does not include definitions with pattern \
         constraints",
    ));
}

fn supported_case(name: &'static str, category: &'static str, passed: bool) -> CompatibilityCase {
    CompatibilityCase {
        name,
        category,
        expected: "pass",
        actual: actual_status(passed),
        status: if passed { "pass" } else { "regression" },
        reason: None,
    }
}

fn expected_gap_case(
    name: &'static str,
    category: &'static str,
    reason: &'static str,
) -> CompatibilityCase {
    CompatibilityCase {
        name,
        category,
        expected: "expected-fail",
        actual: "fail",
        status: "expected-fail",
        reason: Some(reason),
    }
}

fn actual_status(passed: bool) -> &'static str {
    if passed { "pass" } else { "fail" }
}

fn assert_supported_cases_pass(cases: &[CompatibilityCase]) -> Result<(), Box<dyn Error>> {
    let regressions = cases
        .iter()
        .filter(|case| case.expected == "pass" && case.actual != "pass")
        .map(|case| case.name)
        .collect::<Vec<_>>();
    if regressions.is_empty() {
        return Ok(());
    }
    Err(format!("supported compatibility cases regressed: {regressions:?}").into())
}

fn workspace_target_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("target")
}
